version: '3.11'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD_DB}  # Fixed to match web service
      POSTGRES_DB: educam_db           # Fixed to match web service
    healthcheck:                       # Added health check
      test: ["CMD-SHELL", "pg_isready -U postgres -d educam_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy     # Wait for DB to be ready
    environment:
      DB_HOST: db
      DB_NAME: educam_db
      DB_USER: postgres
      DB_PASSWORD: ${PASSWORD_DB}

volumes:
  postgres_data: